//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmenitiesTickets
    {
        public int AmenityID { get; set; }
        public int TicketID { get; set; }
        public decimal Price { get; set; }
    
        public virtual Amenities Amenities { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
